services:
  _defaults:
    public: true

  cdigruttola.module.einvoice.core.domain.command_handler.add_address_customer_type_handler:
    class: 'cdigruttola\Module\Einvoice\Core\Domain\AddressCustomerType\CommandHandler\AddddressCustomerTypeHandler'
    tags:
      - name: tactician.handler
        command: 'cdigruttola\Module\Einvoice\Core\Domain\AddressCustomerType\Command\AddAddressCustomerTypeCommand'

  cdigruttola.module.einvoice.core.domain.query_handler.get_address_customer_type_for_editing:
    class: '\cdigruttola\Module\Einvoice\Core\Domain\AddressCustomerType\QueryHandler\GetAddressCustomerTypeForEditingHandler'
    tags:
      - name: tactician.handler
        command: 'cdigruttola\Module\Einvoice\Core\Domain\AddressCustomerType\Query\GetAddressCustomerTypeForEditing'

  cdigruttola.module.einvoice.core.domain.command_handler.edit_address_customer_type_handler:
    class: 'cdigruttola\Module\Einvoice\Core\Domain\AddressCustomerType\CommandHandler\EditAddressCustomerTypeHandler'
    tags:
      - name: tactician.handler
        command: 'cdigruttola\Module\Einvoice\Core\Domain\AddressCustomerType\Command\EditAddressCustomerTypeCommand'
