imports:
  - { resource: form.yml }
  - { resource: handler.yml }

services:
  _defaults:
    public: true

  cdigruttola.module.einvoice.core.grid.factory.address_customer_type:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - "@cdigruttola.module.einvoice.core.grid.definition.factory.address_customer_type"
      - "@cdigruttola.module.einvoice.core.grid.data_provider.address_customer_type"
      - "@prestashop.core.grid.filter.form_factory"
      - "@prestashop.core.hook.dispatcher"

  cdigruttola.module.einvoice.core.grid.definition.factory.address_customer_type:
    class: 'cdigruttola\Module\Einvoice\Core\Grid\Definition\Factory\AddressCustomerTypeGridDefinitionFactory'
    parent: "prestashop.core.grid.definition.factory.abstract_grid_definition"
    public: true

  cdigruttola.module.einvoice.core.grid.data_provider.address_customer_type:
    class: "%prestashop.core.grid.data.factory.doctrine_grid_data_factory%"
    arguments:
      - "@cdigruttola.module.einvoice.core.grid.query_builder.address_customer_type"
      - "@prestashop.core.hook.dispatcher"
      - "@prestashop.core.grid.query.doctrine_query_parser"
      - "address_customer_type"

  cdigruttola.module.einvoice.core.grid.query_builder.address_customer_type:
    class: 'cdigruttola\Module\Einvoice\Core\Grid\Query\AddressCustomerTypeQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
    public: true
